name: Psalm Security Scan

on: [push, pull_request]

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Psalm – Security Scanner for PHP
        uses: psalm/psalm-github-security-scan@1.2.1
